/**
 * Welcome email sent immediately when a creator joins the waitlist.
 * Goal: make them feel seen, set expectations, build excitement.
 */
function waitlistWelcome({ email, position }) {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f9f9f9;font-family:'Helvetica Neue',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f9f9f9;padding:40px 0;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 6px rgba(0,0,0,0.07);">

        <!-- Header -->
        <tr>
          <td style="background:#7C3AED;padding:32px 40px;">
            <p style="margin:0;font-size:13px;font-weight:700;letter-spacing:0.1em;color:#DDD6FE;text-transform:uppercase;">Vesca</p>
            <h1 style="margin:8px 0 0;font-size:26px;color:#fff;font-weight:800;line-height:1.2;">You're on the list. 🎉</h1>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:36px 40px;">
            ${position ? `<div style="background:#F5F3FF;border-radius:8px;padding:16px 20px;margin-bottom:28px;text-align:center;">
              <p style="margin:0;font-size:13px;color:#6D28D9;font-weight:600;">YOUR WAITLIST POSITION</p>
              <p style="margin:4px 0 0;font-size:36px;font-weight:900;color:#4C1D95;">#${position}</p>
            </div>` : ''}

            <p style="color:#1a1a1a;font-size:16px;line-height:1.75;margin:0 0 20px;">
              Hey creator 👋
            </p>
            <p style="color:#444;font-size:15px;line-height:1.75;margin:0 0 20px;">
              You just secured your spot on the Vesca waitlist — the deal operating system built specifically for creators like you.
            </p>
            <p style="color:#444;font-size:15px;line-height:1.75;margin:0 0 28px;">
              While you wait, here's what Vesca does that no spreadsheet can:
            </p>

            <!-- Feature list -->
            <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
              ${[
                ['📬', 'Cold outreach', 'AI writes your brand pitch in 10 seconds'],
                ['📑', 'Proposals', 'Generate + send a PDF proposal in one click'],
                ['📥', 'Smart inbox', 'AI reads brand emails and extracts the deal details'],
                ['💰', 'Deal pipeline', 'Track every deal from "new" to "paid"'],
              ].map(([icon, title, desc]) => `
              <tr>
                <td style="padding:10px 0;border-bottom:1px solid #F3F4F6;">
                  <table cellpadding="0" cellspacing="0"><tr>
                    <td style="font-size:20px;padding-right:14px;">${icon}</td>
                    <td><strong style="color:#1a1a1a;font-size:14px;">${title}</strong><br>
                    <span style="color:#666;font-size:13px;">${desc}</span></td>
                  </tr></table>
                </td>
              </tr>`).join('')}
            </table>

            <p style="color:#444;font-size:15px;line-height:1.75;margin:0 0 28px;">
              We're onboarding creators in batches. You'll get an email with your access link the moment your spot opens up.
            </p>

            <p style="color:#1a1a1a;font-size:15px;margin:0;">
              Talk soon,<br>
              <strong>Fahd @ Vesca</strong>
            </p>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="padding:20px 40px;border-top:1px solid #F3F4F6;">
            <p style="margin:0;font-size:12px;color:#999;">
              You're receiving this because you signed up at <a href="https://getvesca.com" style="color:#7C3AED;text-decoration:none;">getvesca.com</a>.
              · <a href="mailto:hello@getvesca.com" style="color:#999;">Unsubscribe</a>
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

/**
 * Weekly "Creator Tips" email — sent to the full waitlist every Monday.
 * Content is generated by Claude each week so it never goes stale.
 */
function weeklyCreatorTips({ tipsHtml, weekNumber }) {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f9f9f9;font-family:'Helvetica Neue',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f9f9f9;padding:40px 0;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 6px rgba(0,0,0,0.07);">

        <!-- Header -->
        <tr>
          <td style="border-bottom:3px solid #7C3AED;padding:28px 40px 24px;">
            <table width="100%"><tr>
              <td><span style="font-size:13px;font-weight:700;color:#7C3AED;letter-spacing:0.08em;text-transform:uppercase;">Vesca</span></td>
              <td align="right"><span style="font-size:12px;color:#999;">Week #${weekNumber}</span></td>
            </tr></table>
            <h1 style="margin:12px 0 0;font-size:22px;color:#1a1a1a;font-weight:800;">Creator Deal Tips 💼</h1>
            <p style="margin:6px 0 0;font-size:14px;color:#666;">Your weekly edge for landing better brand deals</p>
          </td>
        </tr>

        <!-- Tips content (Claude-generated HTML) -->
        <tr>
          <td style="padding:32px 40px;color:#333;font-size:15px;line-height:1.75;">
            ${tipsHtml}
          </td>
        </tr>

        <!-- CTA -->
        <tr>
          <td style="padding:0 40px 36px;">
            <div style="background:#F5F3FF;border-radius:8px;padding:20px 24px;">
              <p style="margin:0 0 12px;font-size:14px;color:#4C1D95;font-weight:600;">🚀 Vesca early access is opening soon</p>
              <p style="margin:0;font-size:13px;color:#6D28D9;">You're on the list. We'll email you the moment your spot opens. In the meantime, share Vesca with a creator friend.</p>
              <a href="https://getvesca.com" style="display:inline-block;margin-top:14px;background:#7C3AED;color:#fff;text-decoration:none;padding:10px 22px;border-radius:6px;font-size:13px;font-weight:600;">Visit getvesca.com →</a>
            </div>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="padding:20px 40px;border-top:1px solid #F3F4F6;">
            <p style="margin:0;font-size:12px;color:#999;">
              Sent by <a href="https://getvesca.com" style="color:#7C3AED;text-decoration:none;">Vesca</a>.
              You're on our waitlist — <a href="mailto:hello@getvesca.com?subject=Unsubscribe" style="color:#999;">unsubscribe</a>.
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

/**
 * Access granted email — sent when a waitlist user gets their invite.
 */
function accessGranted({ email }) {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f9f9f9;font-family:'Helvetica Neue',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f9f9f9;padding:40px 0;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 6px rgba(0,0,0,0.07);">

        <tr>
          <td style="background:linear-gradient(135deg,#7C3AED,#A855F7);padding:40px;text-align:center;">
            <p style="margin:0 0 8px;font-size:40px;">🎉</p>
            <h1 style="margin:0;font-size:28px;color:#fff;font-weight:900;">You're in.</h1>
            <p style="margin:8px 0 0;font-size:16px;color:#E9D5FF;">Your Vesca access is ready.</p>
          </td>
        </tr>

        <tr>
          <td style="padding:36px 40px;text-align:center;">
            <p style="color:#444;font-size:15px;line-height:1.75;margin:0 0 28px;">
              The wait is over. Sign up with <strong>${email}</strong> and your account will be ready instantly.
            </p>
            <a href="https://getvesca.com/auth.html" style="display:inline-block;background:#7C3AED;color:#fff;text-decoration:none;padding:16px 36px;border-radius:8px;font-size:16px;font-weight:700;letter-spacing:0.02em;">
              Claim My Access →
            </a>
            <p style="margin:24px 0 0;font-size:13px;color:#999;">Use the email address you signed up with.</p>
          </td>
        </tr>

        <tr>
          <td style="padding:20px 40px;border-top:1px solid #F3F4F6;">
            <p style="margin:0;font-size:12px;color:#999;text-align:center;">
              <a href="https://getvesca.com" style="color:#7C3AED;text-decoration:none;">getvesca.com</a>
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

module.exports = { waitlistWelcome, weeklyCreatorTips, accessGranted };
